# FFT config for Qwen3 4B.
# Some param values are referenced from:
# https://github.com/pytorch/torchtune/blob/main/recipes/configs/qwen3/4B_full.yaml
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi distributed torchrun -m oumi train -c oumi://configs/recipes/qwen3/sft/4b_full/train.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/*train.yaml

# CUDA_VISIBLE_DEVICES=4,5,6,7 oumi distributed torchrun -m oumi train -c "/home/shanghong/oumi/enterprise_experiments/configs/qwen2.5_7b_tatqa.yaml" 2>&1 | tee "/home/shanghong/oumi/enterprise_experiments/logs/qwen2.5_7b_tatqa.log"

model:
  model_name: "Qwen/Qwen2.5-7B-Instruct"
  model_max_length: 16000
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: text_sft_jsonl
        dataset_path: /home/shanghong/oumi/tmp/enterprise_experiments/data/tatqa_train_gpt5mini_think_2.jsonl
    collator_name: "text_completions_only_with_padding"
    collator_kwargs:
      response_template: "<|im_start|>assistant\n"
      instruction_template: "<|im_start|>user\n"
    target_col: "messages"
    seed: 42
  validation:
    datasets:
      - dataset_name: text_sft_jsonl
        dataset_path: /home/shanghong/oumi/tmp/enterprise_experiments/data/tatqa_val_gpt5mini_think_2.jsonl
    collator_name: "text_completions_only_with_padding"
    collator_kwargs:
      response_template: "<|im_start|>assistant\n"
      instruction_template: "<|im_start|>user\n"
    target_col: "messages"
    seed: 42

training:
  # Basic settings
  trainer_type: "TRL_SFT"
  output_dir: "output/qwen2.5_7b.fft_tatqa_think2"
  run_name: "qwen2.5_7b_tatqa_think2"

  # Training duration
  num_train_epochs: 3

  # Batch size settings
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32
  max_grad_norm: 1

  # Mixed precision and performance
  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  compile: False

  # Optimization
  optimizer: "adamw_torch_fused"
  learning_rate: 2e-05
  weight_decay: 0.01

  # Learning rate schedule
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1

  # Evaluation
  eval_strategy: "steps" # When to evaluate ("no", "steps", "epoch")
  eval_steps: 5 # Evaluate every N steps

  # Checkpointing
  save_epoch: True
  save_steps: 0

  # Dataloader settings
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  # Logging
  logging_steps: 1
  enable_wandb: True
  enable_mlflow: True

  # Performance monitoring
  empty_device_cache_steps: 50
  include_performance_metrics: True

fsdp:
  enable_fsdp: True
  forward_prefetch: True
  # cpu_offload: True
  sharding_strategy: "HYBRID_SHARD"
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "Qwen2DecoderLayer"
