model:
  model_name: "Qwen/Qwen3-32B"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True

data:
  train:
    collator_name: "text_completions_only_with_padding"
    collator_kwargs:
      response_template: "<|im_start|>assistant\n"
      instruction_template: "<|im_start|>user\n"
    target_col: "messages"
    seed: 42
  validation:
    collator_name: "text_completions_only_with_padding"
    collator_kwargs:
      response_template: "<|im_start|>assistant\n"
      instruction_template: "<|im_start|>user\n"
    target_col: "messages"
    seed: 42

training:
  # Basic settings
  trainer_type: "TRL_SFT"
  output_dir: "output/qwen3_32b.lora"
  run_name: "qwen3_32b.lora"

  # Training duration
  num_train_epochs: 3

  # Batch size settings
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1

  # Mixed precision and performance
  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  compile: False

  # Optimization
  optimizer: "adamw_torch_fused"
  learning_rate: 5e-05
  weight_decay: 0.01

  # Learning rate schedule
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03

  # Evaluation
  eval_strategy: "steps" # When to evaluate ("no", "steps", "epoch")
  eval_steps: 5 # Evaluate every N steps
  logging_first_step: True

  # Checkpointing
  save_epoch: True
  save_steps: 0

  # Dataloader settings
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  # Logging
  logging_steps: 1
  enable_wandb: True
  enable_mlflow: True

  # Performance monitoring
  empty_device_cache_steps: 50
  include_performance_metrics: True

fsdp:
  enable_fsdp: True
  forward_prefetch: True
  sharding_strategy: "FULL_SHARD"
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "Qwen3DecoderLayer"