model:
  model_name: "Qwen/Qwen2.5-1.5B-Instruct"
  model_max_length: 4096
  load_pretrained_weights: True
  trust_remote_code: True
  attn_implementation: "sdpa"

data:
  train:
    datasets:
      - dataset_name: text_sft_jsonl
        dataset_path: /data/shanghong/oumi/gold/data/train_90.jsonl
        dataset_kwargs:
          return_conversations: True
          return_conversations_format: "dict"
    target_col: "messages"
    seed: 42
  validation:
    datasets:
      - dataset_name: text_sft_jsonl
        dataset_path: /data/shanghong/oumi/gold/data/val_10.jsonl
        dataset_kwargs:
          return_conversations: True
          return_conversations_format: "dict"
    target_col: "messages"
    seed: 42

training:
  # Basic settings
  trainer_type: "TRL_SFT"
  output_dir: "output/countdown_qwen25_15b.sft_disable_completions_only"
  run_name: "countdown_qwen25_15b.sft_disable_completions_only"

  # Training duration
  num_train_epochs: 2

  # Batch size settings
  per_device_train_batch_size: 2 # EBS: 32
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  max_grad_norm: 1

  # Mixed precision and performance
  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  compile: False

  # Optimization
  optimizer: "adamw_torch"
  learning_rate: 1.0e-05

  # Learning rate schedule
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.05

  # Evaluation
  logging_first_step: True
  eval_strategy: "steps" # When to evaluate ("no", "steps", "epoch")
  eval_steps: 100 # Evaluate every N steps

  # Checkpointing
  save_steps: 100

  # Logging
  logging_steps: 1
  enable_wandb: True

  # Performance monitoring
  empty_device_cache_steps: 50
  include_performance_metrics: True

fsdp:
  enable_fsdp: True
  forward_prefetch: True
  sharding_strategy: "HYBRID_SHARD"
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "Qwen2DecoderLayer"
